config:
  name: __MSNAME__-config
  data:
    # Configuration values can be set as key-value properties
    URL_SOCKET_TIMEOUT_MS: '3000'
    URL_MAX_POOL_SIZE: '80'
    URL_MONGO_HOST: 'cluster0.cshmrvk.mongodb.net'
    MONGO_DB_NAME: 'multios-dev'
    MONGO_USERNAME: 'multibulto-user-dev' 
    PRDR_INTEGRATION_MULTIOS_COS_API_URL: 'http://bx-prdr-integration-multios-create-os.dev-ns-integration/api/integration/multios/createos/v1'
    INTEGRATION_OS_LABEL_API_URL: 'http://bx-srv-integration-labels.dev-ns-integration/api/integration/labels/v1'
    ORACLE_HOST: 'cnetdesa.cuo464axjmnt.us-west-2.rds.amazonaws.com'

secret:
  name: __MSNAME__-secret
  data:
    MONGO_USERNAME: #{MONGO_USERNAME}#
    MONGO_PASSWORD: #{MONGO_PASSWORD}#
    ORACLE_USERNAME: #{ORACLE_USERNAME}#
    ORACLE_PASSWORD: #{ORACLE_PASSWORD}#
    ORACLE_PORT: #{ORACLE_PORT}#
    ORACLE_SID: #{ORACLE_SID}#